### ISSUE TITLE
Problem in environment.yml

### ISSUE THREAD

**Issue by luigiquiros** [enpkg/enpkg_sirius_canopus#1]
The line '-GitPython==3.1.31' under pip dependencies should have a space after the hyphen, like '- GitPython==3.1.31'.
the lack of that 'space' generates an error

**Comment by oolonek** [comment]
Ciao Luigi. Thanks for picking this. Adressed https://github.com/enpkg/enpkg_sirius_canopus/commit/6f28f7fa8553f30dea3a768399de5c2083ef27d9
Feel free to directly edit the code if you want. But as said yesterday the best now is to directly look into https://github.com/enpkg/enpkg_full I am working now on this branch https://github.com/enpkg/enpkg_full/tree/enpkg-reprocess-pf1600 and should have a unique yaml to set up all parameters soon.
